package br.ifce.ppd.com.corba;


/**
* br/ifce/ppd/com/corba/MensagemJMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Tuesday, October 15, 2013 11:12:10 PM BRT
*/

public interface MensagemJMSOperations 
{
  boolean criarFila (String arg1);
  String getMensagem (String nome);
  String escreverMensagem (String nome, String msg);
} // interface MensagemJMSOperations
