package br.ifce.ppd.com.corba;


/**
* br/ifce/ppd/com/corba/MensagemJMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Tuesday, October 15, 2013 11:12:10 PM BRT
*/

public interface MensagemJMS extends MensagemJMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MensagemJMS
