package br.ifce.ppd.com.corba;


/**
* br/ifce/ppd/com/corba/MensagemJMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Quarta-feira, 16 de Outubro de 2013 20h22min42s BRT
*/

public interface MensagemJMSOperations 
{
  boolean criarFila (String arg1);
  String getMensagem (String nome);
  String escreverMensagem (String nome, String msg);
  boolean existeFila (String nome);
} // interface MensagemJMSOperations
