package br.ifce.ppd.com.corba;


/**
* br/ifce/ppd/com/corba/MensagemJMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Quarta-feira, 16 de Outubro de 2013 20h22min42s BRT
*/

public interface MensagemJMS extends MensagemJMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MensagemJMS
