package Matematica;


/**
* Matematica/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, October 15, 2013 10:09:22 PM BRT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
