package Matematica;


/**
* Matematica/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, October 15, 2013 10:09:22 PM BRT
*/

public interface CalculadoraOperations 
{
  float soma (float arg1, float arg2);
  float divisao (float arg1, float arg2) throws Matematica.DivisaoPorZero;
} // interface CalculadoraOperations
