package Matematica;


/**
* Matematica/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Segunda-feira, 14 de Outubro de 2013 18h02min34s BRT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
