package Matematica;


/**
* Matematica/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Segunda-feira, 14 de Outubro de 2013 18h02min34s BRT
*/

public interface CalculadoraOperations 
{
  float soma (float arg1, float arg2);
  float divisao (float arg1, float arg2) throws Matematica.DivisaoPorZero;
} // interface CalculadoraOperations
