package Matematica;

/**
* Matematica/DivisaoPorZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Segunda-feira, 14 de Outubro de 2013 18h02min34s BRT
*/

public final class DivisaoPorZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public Matematica.DivisaoPorZero value = null;

  public DivisaoPorZeroHolder ()
  {
  }

  public DivisaoPorZeroHolder (Matematica.DivisaoPorZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Matematica.DivisaoPorZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Matematica.DivisaoPorZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Matematica.DivisaoPorZeroHelper.type ();
  }

}
