package Mensagem;


/**
* Mensagem/MensagemJMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Tuesday, October 15, 2013 10:55:24 PM BRT
*/

public interface MensagemJMSOperations 
{
  boolean criarFila (String arg1);
  String getMensagem (String nome);
  String escreverMensagem (String nome, String msg);
} // interface MensagemJMSOperations
