package Mensagem;


/**
* Mensagem/MensagemJMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Tuesday, October 15, 2013 10:55:24 PM BRT
*/

public interface MensagemJMS extends MensagemJMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MensagemJMS
