package Mensagem;

/**
* Mensagem/MensagemJMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MensagemIDL.idl
* Tuesday, October 15, 2013 10:55:24 PM BRT
*/

public final class MensagemJMSHolder implements org.omg.CORBA.portable.Streamable
{
  public Mensagem.MensagemJMS value = null;

  public MensagemJMSHolder ()
  {
  }

  public MensagemJMSHolder (Mensagem.MensagemJMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Mensagem.MensagemJMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Mensagem.MensagemJMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Mensagem.MensagemJMSHelper.type ();
  }

}
